checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths: [src/*]
    excluded_paths: [vendor/*]

tools:
    php_code_sniffer: true
    php_cs_fixer:
        config: { level: psr2 }
    php_mess_detector: true
    php_pdepend: true
